services:
  mysql:
    container_name: mysql
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: crmcore
    ports:
      - "33060:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"

  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: crmcore
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - postgres
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: >
      sh -c "
        socat TCP-LISTEN:8080,fork,bind=127.0.0.1 TCP:host.docker.internal:8080 & reflex -c reflex.conf
      "

volumes:
  mysql_data:
  pg_data:
