-- migrations/mysql/00001_create_tenants.up.sql
CREATE TABLE IF NOT EXISTS `tenants` (
  `id`          BIGINT AUTO_INCREMENT PRIMARY KEY,
  `slug`        VARCHAR(255) NOT NULL UNIQUE,
  `name`        VARCHAR(255) NOT NULL,
  `domain`      VARCHAR(255),
  `created_at`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


